version: '3.9'
services:
  # docker-proxy:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "${MYSQL_DATA:-/var/lib/mysql}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:

  nextcloud:
    image: nextcloud
    container_name: nextcloud-app
    depends_on:
      - db
    volumes:
      - "${NEXTCLOUD_STORAGE_PATH:-/var/www/html}:/var/www/html"
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: "Host(`${NEXTCLOUD_URL}`)"
      traefik.http.routers.nextcloud.entrypoints: web

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    volumes:
      - ./unloaded_books:/unloaded_books
      - "${CALIBRE_LIBRARY}:/config"
    environment:
      - PUID=33
      - GUID=33
    labels:
      traefik.enable: true
      traefik.http.routers.calibre.rule: "Host(`${CALIBRE_URL}`)"
      traefik.http.routers.calibre.entrypoints: web
      # Below is necessary because the base Dockerfile does not expose any ports
      traefik.http.services.calibre.loadbalancer.server.port: 8080

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    volumes:
      - "${CALIBRE_WEB_LIBRARY}:/books"
    environment:
      - PUID=33
      - GUID=33
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    labels:
      traefik.enable: true
      traefik.http.routers.calibre-web.rule: "Host(`${CALIBRE_WEB_URL}`)"
      traefik.http.routers.calibre-web.entrypoints: web
