version: '3.9'
services:
  docker-proxy:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:

  nextcloud:
    image: nextcloud
    container_name: nextcloud-app
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - /mnt/ncstorage:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    volumes:
      - ./kindle:/kindle
      - ./books:/config
    ports:
      - 8083:8080
    environment:
      - puid=33
      - guid=33

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    volumes:
      - /mnt/ncstorage/data/yevgeny/files/books:/books
    ports:
      - 8084:8083
    environment:
      - PUID=33
      - GUID=33
      - DOCKER_MODS=linuxserver/calibre-web:calibre
